# Generated by Django 4.2.1 on 2023-06-16 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('confirm_password', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('peran', models.CharField(choices=[('Mahasiswa', 'Mahasiswa'), ('Kepala LAB', 'Kepala LAB'), ('Dosen', 'Dosen'), ('Admin', 'Admin')], default='Mahasiswa', max_length=15)),
            ],
            options={
                'db_table': 'pengguna',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id_lab', models.AutoField(primary_key=True, serialize=False)),
                ('nama_lab', models.CharField(max_length=100)),
                ('kepala_lab', models.CharField(max_length=100)),
                ('jumlah_pc', models.IntegerField()),
            ],
            options={
                'db_table': 'lab',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id_mahasiswa', models.AutoField(primary_key=True, serialize=False)),
                ('nim', models.CharField(max_length=30)),
                ('nama', models.CharField(max_length=30)),
                ('kelas', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
            ],
            options={
                'db_table': 'mahasiswa',
            },
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id_mk', models.AutoField(primary_key=True, serialize=False)),
                ('kode_mk', models.CharField(max_length=10)),
                ('nama_mk', models.CharField(max_length=100)),
                ('dosen_pengampu', models.CharField(max_length=100)),
                ('jumlah_sks', models.IntegerField()),
            ],
            options={
                'db_table': 'matakuliah',
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id_pc', models.AutoField(primary_key=True, serialize=False)),
                ('nomor_pc', models.CharField(max_length=50)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.lab')),
            ],
            options={
                'db_table': 'pc',
            },
        ),
        migrations.CreateModel(
            name='Pengcekan',
            fields=[
                ('id_cek', models.AutoField(primary_key=True, serialize=False)),
                ('keterangan', models.CharField(max_length=50)),
                ('deskripsi', models.CharField(max_length=200)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.lab')),
                ('matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.matakuliah')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.pc')),
            ],
            options={
                'db_table': 'pengecekan',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pengcekan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.pengcekan')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
