# Generated by Django 4.2.1 on 2023-06-23 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_pengcekan_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id_dosen', models.AutoField(primary_key=True, serialize=False)),
                ('nip', models.CharField(max_length=30)),
                ('nama', models.CharField(max_length=30)),
                ('jabatan', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dosen',
            },
        ),
    ]
