# Generated by Django 4.2.1 on 2023-06-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_dosen_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='nama',
            field=models.CharField(max_length=100),
        ),
    ]
